### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by twnlink** [uwu/neptune-installer#1]
Currently, `neptune-installer` does support macOS, however it has an issue where it fails to work properly as a result of not having permission to modify the app. We need to add a dialog that requests permission on macOS to make it clearer.

**Comment by calebmasters** [comment]
How do I access the build for macOS? Or is it not available at the moment?

**Comment by twnlink** [comment]
You can build it for macOS locally, the problem with publishing a macOS build is that it has permission issues.

**Comment by StormCreativ** [comment]
So it can or can't be added on mac? If it can, how?

**Comment by edinatl** [comment]
> So it can or can't be added on mac? If it can, how?

I think most of the build/compilation process works except at the end I'm seeing this error on mac:

Error: 'myrouterMatcher (Async)' is not GC-safe as it accesses 'tidalDirectory' which is a global using GC'ed memory
