### ISSUE TITLE
CachyOS (Arch) installation error invalid cross-device link

### ISSUE THREAD

**Issue by MathDesigns** [uwu/neptune-installer#11]
I'm able to execute the installer and select stable, but after i get an error:
CachyOS using Wayland Tidal-Hifi from the AUR

Failed to move injector to app directory!
rename /tmp/neptune-master/injector /opt/tidal-hifi/resources/app: invalid cross-device link

A friend of mine also has the same issue on the same distro with different hardware

Any help would be appreciated

**Comment by smrichards** [comment]
I made a PR with a fix, this should be fixed in the next release or by downloading the repo and building the app manually

**Comment by MathDesigns** [comment]
I investigated a bit yesterday and manage to refactor the code and change the os.Rename() method like you did. I then built it and it worked like a charm. But thanks for providing code and making a PR for everyone !
