### ISSUE TITLE
Tidal won't run with Neptune installed but fine when Neptune uninstalled

### ISSUE THREAD

**Issue by heartmeeting** [uwu/neptune-installer#2]
hi - firstly thank you for this amazing tool.

I've had Neptune installed for about a week with plugins to show the bitrate etc from https://github.com/Inrixia/neptune-plugins

It's been great so far except as of tonight, Tidal wouldn't start - it started to display then got stuck on a black screen. On then uninstalling Neptune it worked perfectly well.

I've tried rebooting as well as reinstalling Tidal over the top, and even uninstalling Tidal fully then reinstalling - nothing has fixed this issue. The only way I can get Tidal to run fully is to uninstall Neptune.

Have you come across this at all? I don't think that there has been an update to Tidal in the last week - i.e. today - which would have killed this.

Many thanks

**Comment by twnlink** [comment]
<img width="1840" alt="image" src="https://github.com/uwu/neptune-installer/assets/31049082/0e5cdce3-cb1c-4401-a52b-63387115f3a3">
Does it look something like this?

**Comment by heartmeeting** [comment]
> <img alt="image" width="1840" src="https://user-images.githubusercontent.com/31049082/267156836-0e5cdce3-cb1c-4401-a52b-63387115f3a3.png"> Does it look something like this?

It looks exactly like that *except I haven't got the three coloured dots at the top left...

**Comment by twnlink** [comment]
Working on it now, 👍🏻

**Comment by heartmeeting** [comment]
Purely out of interest, and not meaning to push you in any way, do you reckon on an ETA? Happy to be told to go away and be patient :-)

**Comment by twnlink** [comment]
> Purely out of interest, and not meaning to push you in any way, do you reckon on an ETA? Happy to be told to go away and be patient :-)

If I don't fix it today it'll be fixed on Wednesday.

**Comment by heartmeeting** [comment]
Thank you so much - really appreciate your efforts.

**Comment by twnlink** [comment]
This issue has been fixed. Wait about 10 minutes before reinstalling neptune and restarting the client and it should work.

**Comment by heartmeeting** [comment]
You are truly heroic - working perfectly now! Thanks again
