### ISSUE TITLE
Tidal reverting to black window after playing several tracks

### ISSUE THREAD

**Issue by heartmeeting** [uwu/neptune-installer#3]
Hi - hope you're well.

Tidal have released a new update recently as I suspect you know, which now shows when playing MAX whether it's MQA or FLAC.

Since that new release, every few songs Tidal's screen goes black as it did before, and is unaccessible although music continues.

On uninstalling Neptune, the issue ceases.

Could you please have a look at this when you have time?

Many thanks

**Comment by twnlink** [comment]
Could you give me a list of plugins you're using? I'd like to attempt to reproduce this issue.

**Comment by heartmeeting** [comment]
It's the two plugins which are at **https://github.com/Inrixia/neptune-plugins**

I believe these aren't your ones but they work well in conjunction with Neptune - I hope that's ok.

One is for showing bitrate and file format (very useful) and one is for showing artwork (less bothered about that one)

Also, I've realised I've logged this issue under the Neptune installer github not the main Neptune one - sorry!

**Comment by heartmeeting** [comment]
Hi - I can see this is closed as completed - does that mean I can now reinstall Neptune and the issue is fixed? Thanks so much
