### ISSUE TITLE
Latest installer just gives blank screen

### ISSUE THREAD

**Issue by Inrixia** [uwu/neptune-installer#5]
![image](https://github.com/uwu/neptune-installer/assets/6373693/7cd3ce4a-288a-40ed-92c7-c616342d26ad)

**Comment by Inrixia** [comment]
![image](https://github.com/uwu/neptune-installer/assets/6373693/a4ef2dc6-2c7c-4c28-9f09-88bb700048a1)

**Comment by itskitchy** [comment]
Hey, I only just noticed you had this issue - are you still having a problem installing it?

**Comment by Inrixia** [comment]
Ah, I forgot to close this. Nope was just adblock.

Thanks for following up!

**Comment by itskitchy** [comment]
No worries, I knew it was an addon of one or another kind - a Hardened Firefox did not want to play along at first either :)
