### ISSUE TITLE
Can't install neptune on windows11

### ISSUE THREAD

**Issue by mtsbh** [uwu/neptune-installer#6]
Hi, I've just found your repo and I tried to install it, but it seems that nothing happens. 

I run the installer and it opened a webpage on which was only one button install neptune. I clicked and got a pop-up saying that I can close this window whenever I want. Then I opened the Tidal app and there's nothing changed. It seems that nothing is installed. 

am I doing something wrong?

**Comment by VTLI** [comment]
same issue

**Comment by twnlink** [comment]
close tidal before installing

**Comment by VTLI** [comment]
oh wow thanks, that was a quick response lol and worked!

**Comment by woeesum** [comment]
i have the same issue but tidal is closed and it still wont install
