### ISSUE TITLE
neptune_installer doesn't work!

### ISSUE THREAD

**Issue by jasonjnag** [uwu/neptune-installer#7]
I'm using win10 desktop.
I downloded exe file in github and I executed, but It says 'neptune failed to inatall make sure to close TIDAL before installing'
but I already closed tidal but it doesn't work, so I tried again after rebooting my system but this also haven't make it.

**Comment by jasonjnag** [comment]
also I turned off ad block in crome!

**Comment by thearccdude** [comment]
I'm experiencing the same issues on my end, tried experimenting with web browsers, restarting and double-checking the task manager but to no avail. 
![Captura de tela 2024-08-06 232724](https://github.com/user-attachments/assets/06ab5f30-154d-46d5-ab09-dfa5a39b2aa4)

**Comment by Inrixia** [comment]
@twnlink Does the installer currently follow 302 redirects when fetching the install payload?

**Comment by Inrixia** [comment]
@jasonjnag @thearccdude I've made a node version of the installer which should work. You can download and use it here https://github.com/Inrixia/neptune-installer-node/releases/latest

If you have any issues running it please open a issue on that repo, or contact me on discord <3

**Comment by twnlink** [comment]
> @twnlink Does the installer currently follow 302 redirects when fetching the install payload?

Yes, the installer follows 302s. There should be no functional difference between your installer and mine besides programming language.

**Comment by tmhamoty** [comment]
@Inrixia I'd just like to thank you for making that Installer. It worked for me. Installing with a custom URL didn't work, however, using the default did. Not sure if this helps. Just thought I'd thank you.

**Comment by Inrixia** [comment]
> @Inrixia I'd just like to thank you for making that Installer. It worked for me. Installing with a custom URL didn't work, however, using the default did. Not sure if this helps. Just thought I'd thank you. 

Thx, yea this was made for people who were having issues with the normal installer so glad it helped!
