### ISSUE TITLE
Installing not working

### ISSUE THREAD

**Issue by PotionsYT** [uwu/neptune-installer#8]
Hi
When i install it, it sends me to a webpage. But all i can see is nothing. just a blank page. Should somthing happen?
I also looked into my console. I even tried a different browser. So im unsure whats going on.

![image](https://github.com/user-attachments/assets/1d1c6efe-70d5-4c0f-a09c-a8607db05c10)

**Comment by twnlink** [comment]
Disable your Brave AdBlocker and then restart the installer.
